predicter:
  eval_csv_path: "/opt/ml/input/data/eval/info.csv"
  eval_img_path: "/opt/ml/input/data/eval/images/"

predict:
  model: 'efficientnet'
  weights:
    age: [save_param/train_base_age/fold1.pt]
    gender: [save_param/train_base_gender/fold1.pt]
    mask: [save_param/train_base_mask/fold1.pt]


  dataloader:
    batch_size: 64
    num_workers: 2


pseudo_labeling_default: &pseudo_labeling_default

  model: 'efficientnet-b0'

  transform:
    crop_size: 350

  dataloader:
    batch_size: 64
    num_workers: 2
  
pseudo_labeling_gender:
  <<: *pseudo_labeling_default
  threshold: [0.9, 0.9]

pseudo_labeling_age:
  <<: *pseudo_labeling_default
  threshold: [0.8, 0.8, 0.8]

pseudo_labeling_mask:
  <<: *pseudo_labeling_default
  threshold: [0.5, 0.95, 0.95]
