targets:
  - "age"
  - "gender"
  - "mask"

trainer:
  train_csv_path: "/opt/ml/input/data/train/train.csv"
  train_img_path: "/opt/ml/input/data/train/images/"
  weight_save_path: "save_param/"
  seed: 42

train_base: &train_base
  model: "efficientnet"

  fold:
    n_splits: 5
    age_bins: [0, 26, 57, 100]

  transform:
    crop_size: 350
    cutout_size: 100

  sampler_size: 0.25

  dataloader:
    batch_size: 64
    num_workers: 2

  optimizer:
    name: "Adam"
    parameters:
      lr: 0.00006

  criterion:
    name: "LabelSmoothing"
    parameters:
      smoothing: 0.05

  train:
    max_epoch: 40
    limit: 10

  weight_save_dir_prefix: train_base_

train_with_pseudo_base: &train_with_pseudo_base
  model: "efficientnet"

  fold:
    n_splits: 3
    age_bins: [0, 29, 59, 100]

  transform:
    crop_size: 350
    cutout_size: 100

  sampler_size: 0.25

  dataloader:
    batch_size: 64
    num_workers: 2

  optimizer:
    name: "Adam"
    parameters:
      lr: 0.00006

  criterion:
    name: "LabelSmoothing"
    parameters:
      smoothing: 0.05

  train:
    max_epoch: 40
    patience: 10

  weight_save_dir_prefix: pseudo_

train_gender: *train_base

train_mask: *train_base

train_age:
  <<: *train_base
  fold:
    n_splits: 5
    age_bins: [0, 26, 57, 100]

train_with_pseudo_gender: *train_with_pseudo_base

train_with_pseudo_mask: *train_with_pseudo_base

train_with_pseudo_age:
  <<: *train_with_pseudo_base
  fold:
    n_splits: 2
    age_bins: [0, 26, 57, 100]
